services:
  postgres:
    image: postgres:17
    container_name: postgres_db_Yummy
    environment:
      POSTGRES_DB: ${DB_NAME:-Demo-DB}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-1234}
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadminYummy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_ENABLE_CSRF: "false" 
    ports:
      - "5050:80"
    networks:
      - app-network

  app:
    build:
      context: . 
      dockerfile: ./Dockerfile # Ruta específica al archivo Dockerfile
    container_name: app_MobilityInc
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-Demo-DB}
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-1234}
      NODE_ENV: development
    ports:
      - "3001:3000" 
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
