services:
  postgres:
    image: postgres:17
    container_name: postgres_db_Yummy
    environment:
      POSTGRES_DB: ${DB_NAME:-Pagos-DB}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-1234}
    ports:
      - "${DB_PORT:-5433}:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadminYummy
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "5050:80"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network: